### ISSUE TITLE
archives listing on home page?

### ISSUE THREAD

**Issue by asifdev124** [madi-nuralin/lms#1]
@madi-nuralin how can we get  the list of archives on the home page? for example 8 most recent issues to be displayed on the home page, just the cover and the title, 4 in a row, can you please send me code snippet? thank you in advance

**Comment by madi-nuralin** [comment]
I think you're asking from another repo issue page. Did you mean [https://github.com/madi-nuralin/material](https://github.com/madi-nuralin/material) ? If so, could you open the issue from that page?

**Comment by asifdev124** [comment]
@madi-nuralin yes apologies, I have created issue there, TIA
